export const MARK_FORM_DIRTY = 'FORM_STATE/MARK_FORM_DIRTY';

export const MARK_FORM_SUBMITTED = 'FORM_STATE/MARK_FORM_SUBMITTED';

export const ADD_TOUCHED_FIELDS = 'FORM_STATE/ADD_TOUCHED_FIELDS';

export const SET_SUBMIT_COUNT = 'FORM_STATE/SET_SUBMIT_COUNT';

export const SET_FORM_VALID = 'FORM_STATE/SET_FORM_VALID';
