name: Run Test on Pull Request

on:
  pull_request:
    branches: master

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - run: yarn install
      - run: yarn test
